/* eslint-disable max-len */
const subindicatorOptions = [
	'Aboveground Biomass',
	'Agronomic Efficiency',
	'Animal Mortality',
	'Animal Survival',
	'Belowground Biomass',
	'Beneficial Organisms',
	'Benefit Cost Ratio (GRTC)',
	'Benefit Cost Ratio (GRVC)',
	'Benefit Cost Ratio (NRTC)',
	'Benefit Cost Ratio (NRVC)',
	'Biodiversity',
	'Biomass Yield',
	'Carbon dioxide emissions',
	'Cation Exchange Capacity',
	'CO2 Equivalent Emissions',
	'Cooking Time',
	'Cookstove Emissions',
	'Cost Benefit Ratio (TCGR)',
	'Cost Benefit Ratio (TCNR)',
	'Cost Benefit Ratio (VCGR)',
	'Cost Benefit Ratio (VCNR)',
	'Crop Yield',
	'Egg Yield',
	'Emissions Intensity',
	'Erosion',
	'Feed Conversion Ratio (In Out)',
	'Feed Conversion Ratio (Out In)',
	'Fixed Cost',
	'Fuel Savings',
	'Fuel Use',
	'Gross Margin',
	'Gross Return',
	'Income Female',
	'Income Male',
	'Infiltration Rate',
	'Internal Rate of Return',
	'Isotopic NUE (AGB)',
	'Isotopic NUE (Product)',
	'Labour Cost',
	'Labour Female',
	'Labour Male',
	'Labour Person Hours',
	'Labour Value',
	'Marginal Rate of Return',
	'Meat Yield',
	'Methane Emissions',
	'Milk Yield',
	'Net Present Value',
	'Net Return',
	'Nitrogen (Apparent Efficiency)',
	'Nitrogen ARE (AGB)',
	'Nitrogen ARE (Product)',
	'Nitrogen ARE (Unspecificed)',
	'Nitrogen Factor Productivity',
	'Nitrous Oxide Emissions',
	'Other Animal Product Yield',
	'Partial Nitrogen Balance (AGB)',
	'Partial Nitrogen Balance (Product)',
	'Payback Period',
	'Pest & Pathogen (Losses)',
	'Pest & Pathogen (Numbers)',
	'Pest & Pathogen (Product Weight)',
	'Phosphorus ARE (Product)',
	'Phosphorus ARE (Unspecificed)',
	'Phosphorus Recovery Efficiency (AGB)',
	'Protein Conversion Ratio (In Out)',
	'Protein Conversion Ratio (Out In)',
	'Reproductive Yield',
	'Return on Investment',
	'Runoff',
	'Soil Available Nitrogen',
	'Soil Carbon Stocks',
	'Soil Moisture',
	'Soil NH4',
	'Soil NO3',
	'Soil Organic Carbon',
	'Soil Organic Carbon (Change)',
	'Soil Organic Matter',
	'Soil Total Nitrogen',
	'Specific Fuel Use',
	'Subindicator',
	'Total Cost',
	'Total Factor Productivity',
	'Variable Cost',
	'Water Use (Irrigation)',
	'Water Use (Total)',
	'Water Use (Unspecified)',
	'Water Use Efficiency',
	'Weight Gain',
	'Yield Stability',
];

const configurationLivestock =	{
	header: 'Outcomes',
	id: 'feec0c82-0fbf-475f-a3e4-3331ed601438',
	content: [
		{
			id: '81c21c9e-257f-4ba4-ae07-90706c7e3da0',
			type: 'header',
			text: 'Outcome Description',
			category: 'p',
			size: '18px',
			weight: 'bold',
			data: true,
		},
		{
			id: '55c0c7f9-95b9-471c-bb51-a4ce0d1a4f4f',
			type: 'expandable-table',
			label: '',
			fieldInformation: '',
			valid: false,
			editable: true,
			headerButtonLabel: 'Add Indicator',
			placeholder: 'Press Add Indicator',
			deleteMessage: 'Do you want to delete this indicator?',
			data: 'table',
			columns: [
				{
					id: 'c9a5bdbe-044d-40fd-9b46-4cee6d2b9256',
					data: true,
					type: 'list',
					label: 'Outcome',
					options: subindicatorOptions.map((item) => ({ value: item })),
					filter: true,
				},
				{
					id: 'c2c639af-446d-4d51-a80f-870b74e67ac8',
					data: true,
					type: 'text',
					label: 'Outcome Name',
					subIndex: true,
					generatedFrom: { outcomeNameFunc(helperContext, stepValues) {
						const id = helperContext.helperState.outcomeId;
						const temp = stepValues.get('c2c639af-446d-4d51-a80f-870b74e67ac8');
						if (!temp?.value) {
							return `Outcome ${id}`;
						}
						return undefined;
					} },
				},
			],
			content: [
				{
					id: '930e3bff-b271-440d-9767-053391e0d5f1',
					type: 'text',
					label: 'Unit',
					fieldInformation: ' ',
					valid: false,
					data: true,
				},
				{
					id: 'bdfb0be0-4a80-40d5-8abc-67ddc7348f45',
					type: 'text',
					label: 'Species/Item/Group',
					fieldInformation: ' ',
					valid: false,
					data: true,
				},
				{
					id: '021ec465-6f68-452e-bd42-9317997e16b0',
					type: 'text',
					label: 'Formula',
					fieldInformation: ' ',
					valid: false,
					data: true,
				},
				{
					id: '7a00ecfd-4dbb-4e2a-8a84-9c0d2783f6e8',
					type: 'header',
					text: 'Soil Outcome Depths (cm)',
					category: 'p',
					size: '16px',
					weight: '500',
				},
				{
					id: 'e964b054-7339-4272-8ea4-eaaf8fbb5b77',
					type: 'text',
					label: 'Upper',
					fieldInformation: ' ',
					valid: false,
					data: true,
				},
				{
					id: 'de5266a6-db3c-4f38-9753-49074af9afe2',
					type: 'text',
					label: 'Lower',
					fieldInformation: ' ',
					valid: false,
					data: true,
				},
				{
					type: 'divider',
					horizontal: true,
					style: { margin: '8px 0px' },
				},
				{
					id: 'c2e90f46-20cb-4660-8356-8f0951da34f7',
					type: 'list',
					label: 'Economic Data Calculation Method',
					fieldInformation: ' ',
					options: ['Averaged across time period', 'Summed across time period'],
					filter: false,
					data: true,
				},
				{
					id: '5d9897ec-1af6-43c4-a36f-740f15f7d128',
					type: 'list',
					label: 'Currency',
					fieldInformation: ' ',
					options: ['Vocabulary'],
					filter: true,
					data: true,
				},
				{
					id: '4b308e18-2118-488d-bca8-1b41c327e54a',
					type: 'number',
					label: 'USD Exchange Rate',
					data: true,
					fieldInformation: ' ',
					fractionDigits: 3,
				},
				{
					id: 'a0a15211-4ce8-4d99-81a7-4efbf5227cd3',
					type: 'text area',
					label: 'Description of partial outcomes (usually economic)',
					fieldInformation: ' ',
					valid: false,
					data: true,
				},
				{
					id: '250aa80e-b78f-48f4-95da-aed9cf251570',
					type: 'header',
					text: 'NPV',
					category: 'p',
					size: '16px',
					weight: '500',
				},
				{
					id: 'dc78bb50-a193-4078-9536-96b873adc8f3',
					type: 'text',
					label: 'Discount Rate (%)',
					fieldInformation: ' ',
					valid: false,
					linkedField: { id: 'c9a5bdbe-044d-40fd-9b46-4cee6d2b9256', targetValue: ['Net Present Value'] },
					disabled: true,
					data: true,
				},
				{
					id: '426d20e2-fd1c-4e07-8532-fc22d81ba8b9',
					type: 'text',
					label: 'Period (Year)',
					fieldInformation: ' ',
					valid: false,
					linkedField: { id: 'c9a5bdbe-044d-40fd-9b46-4cee6d2b9256', targetValue: ['Net Present Value'] },
					linkedValue: 'Net Present Value',
					disabled: true,
					data: true,
				},
				{
					id: 'c053bad1-9865-4602-bd60-91564c1c1b4b',
					type: 'header',
					text: 'Weight Gain',
					category: 'p',
					size: '16px',
					weight: '500',
					data: true,
				},
				// {
				// 	id: 'e52d631b-2892-4134-acd2-d8554d06d918',
				// 	type: 'text',
				// 	label: 'Mean Starting Weight',
				// 	fieldInformation: ' ',
				// 	valid: false,
				// 	linkedField: { id: 'c9a5bdbe-044d-40fd-9b46-4cee6d2b9256', targetValue: ['Weight Gain', 'Meat Yield'] },
				// 	disabled: true,
				// 	data: true,
				// },
				// {
				// 	id: '0c2c838f-1de4-43f6-9a46-27819447a3ad',
				// 	type: 'text',
				// 	label: 'Starting Weight Unit',
				// 	fieldInformation: ' ',
				// 	valid: false,
				// 	linkedField: { id: 'c9a5bdbe-044d-40fd-9b46-4cee6d2b9256', targetValue: ['Weight Gain', 'Meat Yield'] },
				// 	disabled: true,
				// 	data: true,
				// },
				{
					id: '67c062ff-b823-4bd6-aee6-0858ed11014b',
					type: 'text',
					label: 'Duration (Days)',
					fieldInformation: ' ',
					valid: false,
					linkedField: { id: 'c9a5bdbe-044d-40fd-9b46-4cee6d2b9256', targetValue: ['Weight Gain', 'Meat Yield'] },
					disabled: true,
					data: true,
				},
			],
		},
		{
			id: '7d42c091-e003-4f66-9e65-f7393712f546',
			type: 'header',
			text: 'Economic Costs and Benefits',
			category: 'p',
			size: '18px',
			weight: 'bold',
			data: true,
		},
		{
			id: 'a3f88dd5-0286-40d6-bbc3-cbbf874e5f03',
			type: 'input-table',
			label: '',
			fieldInformation: '',
			valid: true,
			data: 'table',
			headerButtonLabel: 'Add Row',
			placeholder: 'Press Add Row',
			deleteMessage: 'Do you want to delete this row?',
			floatingLabel: 'Toggle visible Columns',
			columns: [
				{ field: 'site', header: 'Site', info: '' },
				{ field: 'category', header: 'Variable Category', info: '' },
				{ field: 'variable', header: 'Variable', info: '' },
				{ field: 'variable_details', header: 'Variable Details', info: '' },
				{ field: 'value', header: 'Value', info: '' },
				{ field: 'unit', header: 'Unit', info: '' },
				{ field: 'timeframe', header: 'Timeframe', info: '' },
				{ field: 'year', header: 'Year', info: '' },
			],
			content: [
				{
					id: '255fb141-ee7b-4571-bc55-b75a00f3e899',
					type: 'list',
					label: '',
					fieldInformation: '',
					data: true,
					valid: false,
					col: 'site',
					options: ['Work in progress.'],
				},
				{
					id: 'ec18e0ee-a184-4fa8-8ae4-fde8bf0aa6c0',
					type: 'list',
					label: '',
					fieldInformation: '',
					data: true,
					valid: false,
					col: 'category',
					options: ['Work in progress.'],
				},
				{
					id: '3bcef50b-bc7d-40a1-8785-ab1ad30bb4e4',
					type: 'list',
					label: '',
					fieldInformation: '',
					data: true,
					valid: false,
					col: 'variable',
					options: ['Work in progress.'],
					definition: {

					},
				},
				{
					id: 'f8cfd56e-5bd0-45ea-88b3-fbcf5261b46d',
					type: 'text',
					label: '',
					fieldInformation: '',
					valid: false,
					col: 'variable_details',
					data: true,
				},
				{
					id: '76824776-f811-4ddb-8d14-43740ee789e4',
					type: 'text',
					label: '',
					fieldInformation: '',
					valid: false,
					col: 'value',
					data: true,
				},
				{
					id: 'df483b81-56e0-47d8-9c8c-537d7c7dfe31',
					type: 'text',
					label: '',
					fieldInformation: '',
					valid: false,
					col: 'unit',
					data: true,
				},
				{
					id: '302f1628-7f00-4bd4-a0ac-7fa7960855c9',
					type: 'list',
					label: '',
					fieldInformation: '',
					data: true,
					valid: false,
					col: 'timeframe',
					options: ['Work in progress.'],
				},
				{
					id: 'e5cc659e-cfaf-4a49-a3a4-de23d7460fc0',
					type: 'text',
					label: '',
					fieldInformation: '',
					valid: false,
					col: 'year',
					data: true,
				},
			],
		},
	],
};

export default configurationLivestock;
