const configurationLivestock = {
	id: 'cb718d89-dbbf-41d3-a2c5-044ef8578a21',
	type: 'input-table',
	label: '',
	fieldInformation: '',
	valid: true,
	data: 'table',
	headerButtonLabel: 'Add Time Period',
	placeholder: 'Press Add Time Period',
	deleteMessage: 'Do you want to delete this season?',
	floatingLabel: 'Toggle visible Columns',
	columns: [
		{ field: 'period_name', header: 'Time Period Name', info: '' },
		{ field: 'start_date', header: 'Start Date (dd/mm/yyyy)', info: '' },
		{ field: 'end_date', header: 'End Date (dd/mm/yyyy)', info: '' },
		{ field: 'description', header: 'Period Description', info: 'Time period description such as dry, rainy or cold season.' },
		{ field: 'rainfall', header: 'Rainfall (mm)', info: '' },
		{ field: 'max_temp', header: 'Mean Max Temp (°C)', info: '' },
		{ field: 'mean_temp', header: 'Mean Temp (°C)', info: '' },
		{ field: 'min_temp', header: 'Mean Min Temp (°C)', info: '' },
	],
	content: [
		{
			id: '5fec44e2-cb3c-42ee-91cf-e29c2b1dae54',
			type: 'text',
			label: '',
			fieldInformation: '',
			data: true,
			valid: false,
			col: 'period_name',
		},
		{
			id: '4b14928e-a025-43ca-94a8-d41fbc2d3e53',
			data: true,
			type: 'calendar',
			mandatory: false,
			year: false,
			valid: true,
			maxDate: true,
			col: 'start_date',
		},
		{
			id: 'a87f042e-25e6-42b2-8c3d-4e7df74ceba3',
			data: true,
			type: 'calendar',
			mandatory: false,
			year: false,
			valid: true,
			maxDate: true,
			col: 'end_date',
		},
		{
			id: 'd5cdffca-55c4-4b95-9bbd-2b6e013a398e',
			type: 'text',
			label: '',
			fieldInformation: '',
			data: true,
			valid: false,
			col: 'description',
		},
		{
			id: 'd0d00b8b-eb67-4f90-b548-d1044a1c7d25',
			type: 'number',
			// minNumber: 1,
			label: '',
			data: true,
			fieldInformation: '',
			valid: false,
			fractionDigits: 3,
			col: 'rainfall',
		},
		{
			id: 'dd374dc9-3034-496d-b008-0a3add8d1f5c',
			type: 'number',
			// minNumber: 1,
			label: '',
			data: true,
			fieldInformation: '',
			valid: false,
			fractionDigits: 3,
			col: 'max_temp',
		},
		{
			id: 'a31ae18b-eb74-4352-94ec-586dd2d0653f',
			type: 'number',
			// minNumber: 1,
			label: '',
			data: true,
			fieldInformation: '',
			valid: false,
			fractionDigits: 3,
			col: 'mean_temp',
		},
		{
			id: 'e48750a4-e976-403c-b313-dfdc5814cf76',
			type: 'number',
			// minNumber: 1,
			label: '',
			data: true,
			fieldInformation: '',
			valid: false,
			fractionDigits: 3,
			col: 'min_temp',
		},
	],
};

export default configurationLivestock;
