const configurationLivestock = 	{
	header: 'Experimental Design',
	content: [
		{
			id: '2a937a5a-ac20-432b-817e-ad7cabe8d441',
			type: 'tabs',
			data: false,
			label: 'Design Tabs',
			fieldInformation: '',
			valid: false,
			tabs: [
				{
					header: 'General Design',
					id: '7c94adb7-890b-45d1-8120-fe82fbd9af67',
					content: [
						{
							id: 'a2aa8a78-3c67-4434-9b33-e5821c94ae1e',
							type: 'text',
							label: 'Experimental Design',
							fieldInformation: ' ',
							data: true,
							valid: false,
						},
						{
							id: 'e173748f-8795-4c9d-a9c6-18a797f6d31c',
							type: 'text',
							label: 'Acclimatization',
							fieldInformation: ' ',
							data: true,
							valid: false,
						},
						{
							id: 'c9df8dc5-4068-46d7-aae6-96316307dc30',
							type: 'text area',
							label: 'Design Notes',
							fieldInformation: ' ',
							data: true,
							valid: false,
						},
						// {
						// 	id: '453317bf-6322-42a2-98ea-44a609b505cc',
						// 	type: 'header',
						// 	text: 'Rationale for Animal Feed Experiments',
						// 	category: 'p',
						// 	size: '18px',
						// 	weight: 'bold',
						// },
						{
							id: '2e85cb33-5752-4c4e-b2dc-7bce0b584b31',
							type: 'multi-list',
							data: true,
							label: 'Rationale for Animal Feed Experiments',
							fieldInformation: ' ',
							options: [
								'Increased Energy',
								'Increased Protein',
								'Increased Digestibility',
								'Reduced Costs',
							],
							valid: false,
						},
						// {
						// 	id: '0ed47ef5-2bcc-41a2-a775-c32c1a201a5c',
						// 	type: 'list',
						// 	data: true,
						// 	label: 'Increased Protein',
						// 	fieldInformation: ' ',
						// 	maxWords: 1,
						// 	options: [
						// 		'Yes',
						// 		'No',
						// 	],
						// 	valid: false,
						// },
						// {
						// 	id: '050e6dba-aa2a-43ec-832e-3a5a411c1380',
						// 	type: 'list',
						// 	data: true,
						// 	label: 'Increased Digestibility',
						// 	fieldInformation: ' ',
						// 	maxWords: 1,
						// 	options: [
						// 		'Yes',
						// 		'No',
						// 	],
						// 	valid: false,
						// },
						// {
						// 	id: 'f248c3af-84b1-408f-b64c-7640d49954fa',
						// 	type: 'list',
						// 	data: true,
						// 	label: 'Reduced Costs',
						// 	fieldInformation: ' ',
						// 	maxWords: 1,
						// 	options: [
						// 		'Yes',
						// 		'No',
						// 	],
						// 	valid: false,
						// },
						// {
						// 	id: '316ab4aa-4efa-471a-af9c-753d1b18f552',
						// 	type: 'header',
						// 	text: 'Are any aspects of the diet kept the same between control and experiment?',
						// 	category: 'p',
						// 	size: '18px',
						// 	weight: 'bold',
						// },
						{
							id: 'f248c3af-84b1-408f-b64c-7640d49954fa',
							type: 'multi-list',
							data: true,
							label: 'Aspects of the diet kept the same between control and experiment',
							fieldInformation: ' ',
							options: [
								'Weight or amount fed',
								'Energy Content',
								'Protein or Nitrogen Content',
								'Cost',
								'Dry Matter Content',
							],
							valid: false,
						},
						// {
						// 	id: '63c068b2-e7b1-4167-b86c-51bb2c398637',
						// 	type: 'list',
						// 	data: true,
						// 	label: '',
						// 	fieldInformation: ' ',
						// 	maxWords: 1,
						// 	options: [
						// 		'Yes',
						// 		'No',
						// 	],
						// 	valid: false,
						// },
						// {
						// 	id: '511c7dd5-4224-4d4a-b25e-c4dc00541d3f',
						// 	type: 'list',
						// 	data: true,
						// 	label: '',
						// 	fieldInformation: ' ',
						// 	maxWords: 1,
						// 	options: [
						// 		'Yes',
						// 		'No',
						// 	],
						// 	valid: false,
						// },
						// {
						// 	id: '888e59f4-e9f5-46c9-a9d3-1fa93bd3aa16',
						// 	type: 'list',
						// 	data: true,
						// 	label: 'Cost',
						// 	fieldInformation: ' ',
						// 	maxWords: 1,
						// 	options: [
						// 		'Yes',
						// 		'No',
						// 	],
						// 	valid: false,
						// },
						// {
						// 	id: '255affe5-8529-4cec-b36f-7d2671ebca18',
						// 	type: 'list',
						// 	data: true,
						// 	label: 'Dry Matter Content',
						// 	fieldInformation: ' ',
						// 	maxWords: 1,
						// 	options: [
						// 		'Yes',
						// 		'No',
						// 	],
						// 	valid: false,
						// },
						// {
						// 	id: 'd6a1784c-c64f-40f0-b41a-32c1ee66bf28',
						// 	type: 'header',
						// 	text: 'Do the authors state this is a feed addition or substitution experiment?',
						// 	category: 'p',
						// 	size: '18px',
						// 	weight: 'bold',
						// },
						{
							id: '7a1739e3-1433-4caa-8516-ddacae4ee3ec',
							type: 'list',
							data: true,
							label: 'Do the authors state this is a feed addition or substitution experiment?',
							fieldInformation: ' ',
							maxWords: 1,
							options: [
								'Feed Addition',
								'Feed Substitution',
							],
							valid: false,
						},
						// {
						// 	id: 'a7616ec8-a504-4857-82d9-0468a064e29a',
						// 	type: 'list',
						// 	data: true,
						// 	label: 'Feed Substitution',
						// 	fieldInformation: ' ',
						// 	maxWords: 1,
						// 	options: [
						// 		'Yes',
						// 		'No',
						// 	],
						// 	valid: false,
						// },
					],
				},
				{
					header: 'System & Housing',
					id: 'e0d04bb7-5e8e-4dd5-b344-a6e3ea30da2d',
					content: [
						{
							id: '39694d16-ca57-4fca-9d2b-5f4e85901f35',
							type: 'text',
							label: 'System Name',
							fieldInformation: ' ',
							data: true,
							valid: false,
						},
						{
							id: 'a370642c-903a-4448-88d4-6e88f8a30468',
							type: 'list',
							data: true,
							label: 'Production System Type',
							fieldInformation: ' ',
							maxWords: 1,
							options: [
								'Work in progress',
							],
							valid: false,
						},
						{
							id: '473648eb-23d2-4f13-ac5f-0512fb72a4a1',
							type: 'list',
							data: true,
							label: 'Rearing System',
							fieldInformation: ' ',
							maxWords: 1,
							options: [
								'Work in progress',
							],
							valid: false,
						},
						{
							id: '88b9d4ba-34a3-428b-af3b-a6a59fb3728e',
							type: 'list',
							data: true,
							label: 'Species Association',
							fieldInformation: ' ',
							maxWords: 1,
							options: [
								'Work in progress',
							],
							valid: false,
						},
						{
							id: 'ec8f3882-2023-456d-aa7e-f7d3d25224e5',
							type: 'list',
							data: true,
							label: 'Rearing or Housing Structure',
							fieldInformation: ' ',
							maxWords: 1,
							options: [
								'Work in progress',
							],
							valid: false,
						},
						{
							id: 'dbfbe3a0-84bf-4674-a26f-174747b9536e',
							type: 'list',
							data: true,
							label: 'Rearing or Housing System',
							fieldInformation: ' ',
							maxWords: 1,
							options: [
								'Work in progress',
							],
							valid: false,
						},
						{
							id: 'abd257d6-ec6c-4f56-adef-193080fb22b6',
							type: 'list',
							data: true,
							label: 'For animals housed in structures: Fans or other cooling methods directly mentioned in the methods?',
							fieldInformation: ' ',
							maxWords: 1,
							options: [
								'Work in progress',
							],
							valid: false,
						},
					],
				},
			],
		},
	],
};

export default configurationLivestock;
