const configuration = {
	header: 'Trees',
	id: 'ca4e4a50-b419-4fa2-804a-b97664066f33',
	description: false,
	content: [
		{
			id: 'd59ff545-246d-4add-91dc-ae64633ce9e9',
			data: true,
			type: 'text',
			label: 'Practice Name',
			fieldInformation: ' ',
		},
		{
			id: '97db9486-10ff-4b1b-8791-d2a5f7efad56',
			type: 'list',
			label: 'Boundary Planting',
			fieldInformation: ' ',
			valid: false,
			data: true,
		},
		{
			id: 'd27b7c0f-df88-41a0-b624-533a8916bdf3',
			type: 'list',
			label: 'Aquasilviculture',
			fieldInformation: ' ',
			valid: false,
			data: true,
		},
		{
			id: 'bf872adb-3c9c-453c-b47f-be3cb2296c9d',
			type: 'list',
			label: 'Other Agroforestry',
			fieldInformation: ' ',
			valid: false,
			data: true,
		},
		{
			id: '682b1d0e-cb1e-4044-bcbd-7b4dd3aae511',
			type: 'text area',
			label: 'Notes',
			fieldInformation: ' ',
			valid: false,
			data: true,
		},
		{
			id: '1810d295-e82a-4a28-89c5-c44864a5ded6',
			type: 'input-table',
			label: '',
			fieldInformation: '',
			valid: true,
			headerButtonLabel: 'Add Row',
			placeholder: 'Press Add Row',
			deleteMessage: 'Do you want to delete this row?',
			data: 'table',
			columns: [
				{ field: 'tree_shrub', header: 'Tree or Shrub', info: '' },
				{ field: 'subspecies', header: 'Subspecies', info: '' },
				{ field: 'variety', header: 'Variety', info: '' },
				{ field: 'number', header: 'Number', info: '' },
				{ field: 'notes', header: 'Notes', info: '' },
			],
			content: [
				{
					id: '20b8794a-28a0-4e78-8189-13160c7fa1c2',
					type: 'list',
					label: '',
					fieldInformation: '',
					keyword: 'trees',
					valid: false,
					col: 'tree_shrub',
					data: true,
				},
				{
					id: '75ec5e33-18dd-4aa4-8497-b0225853e5a3',
					type: 'list',
					label: '',
					fieldInformation: '',
					keyword: 'agroforestry_subspecies',
					valid: false,
					col: 'subspecies',
					data: true,
				},
				{
					id: '2e647967-2ec9-4c47-89fa-f78ba3401ff8',
					type: 'list',
					label: '',
					fieldInformation: '',
					keyword: 'tree_variety',
					valid: false,
					col: 'variety',
					data: true,
				},
				{
					id: '1bfac186-2b10-45f1-9267-26410cb00c5c',
					type: 'number',
					valid: false,
					columnNumber: 0,
					data: true,
					options: ['Work in progress'],
					units: 'self',
					col: 'number',
				},
				{
					id: 'dbbceab6-b3f7-476b-b5c9-0321d11317e0',
					data: true,
					type: 'text',
					col: 'notes',
				},
			],
		},
	],
};

export default configuration;
